### ISSUE TITLE
non-existing PPS 0 referenced

### ISSUE THREAD

**Issue by helldog136** [bakjos/FFMPEGMedia#1]
Hi,

I just found your plugin and i plan on using it for my master's thesis. The plan is to stream video from a camera from another computer and display it inside an unreal engine app. 

The video stream is sent from a python app doing some magic stuff with openCV then piping the stream in ffmpeg for him to send the video.

Currently i stream the video using this command:
ffmpeg -hide_banner -i pipe:0 -an -f h264 udp://127.0.0.1:1234/l.mp4

I can see the stream using ffplay using the command
ffplay -i udp://127.0.0.1:1234/l.mp4

However when i try to get the stream using UE4 StreamMediaSource with ffmpeg the image stays black and i get the following error:
LogFFMPEGMedia: Error: FFMPEG - non-existing PPS 0 referenced
LogFFMPEGMedia: Error: FFMPEG - non-existing PPS 0 referenced
LogFFMPEGMedia: Error: FFMPEG - decode_slice_header error
LogFFMPEGMedia: Error: FFMPEG - no frame!

Do you have any idea of what i did wrong? Or is this a bug?

Thanks
Helldog136

**Comment by helldog136** [comment]
Did not found a solution but changed the way i stream my video so i close this thread

**Comment by bakjos** [comment]
Hi, I've just made a small test, streaming a file with the same command you were using but instead of pipe0 I use a local file  and it worked well for me, It may have something to do with the version of ffmpeg you're streaming with (I'm using the 4.0) or with the original file itself. Have you tried to use a local file instead, to be sure the plugin is setup correctly?
