### ISSUE TITLE
Specifying decoder

### ISSUE THREAD

**Issue by PTS93** [bakjos/FFMPEGMedia#7]
First of all thank you very much for this plugin, video playback options are still very lacking for UE4.
I was wondering if there is any way to specify which codec/decoder is being used. Worst case be that I have to hard code it somewhere.

Any pointers would be much appreciated.

**Comment by bakjos** [comment]
@PTS93  Sorry for all the delay to answer, I haven't include the options to select the codec because I wanted this process to be automatic (just to choose if you want accelelerated drivers or not), and PRs for this are more than welcome.  I'm using this function to get all the available decoders for a  [file](https://github.com/bakjos/FFMPEGMedia/blob/161c5d1acb42f1aae0708b3f03abb638f58d2425/Source/FFMPEGMedia/Private/Player/FFMPEGMediaTracks.cpp#L1328), but is only happening when the UseHardwareAcceleratedCodecs  option is enabled. You can move the function and always find the codec (passing some filtering options)

**Comment by PTS93** [comment]
Thanks! I didn't see the flag for hardware acceleration, that might actually be enough for my usecase. Thanks for the pointer though, I might take a look at adding options for specific codecs.
